services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"  # Using 11435 on host to avoid conflicts with existing Ollama
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # Increased start period
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=http://ollama:11434  # This points to the Ollama service
      - MODEL_NAME=qwen:1.8b
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    volumes:
      - ./:/app  # Mount current directory to /app
    networks:
      - ai-network
    restart: unless-stopped

networks:
  ai-network:
    driver: bridge

volumes:
  ollama_data: